# Generated by Django 4.2.2 on 2023-06-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figura',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('origen', models.CharField(max_length=50, verbose_name='Origen')),
                ('fabricante', models.CharField(max_length=50, verbose_name='Fabricante')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('escala', models.CharField(max_length=50, verbose_name='escala')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripción')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
            ],
        ),
    ]
