# Generated by Django 4.2.2 on 2023-07-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'Consulta'], [1, 'Reclamo'], [2, 'Sugerencia'], [3, 'Felicitacion']], verbose_name='Tipo de consulta')),
                ('mensaje', models.TextField(max_length=1000, verbose_name='Mensaje')),
                ('avisos', models.BooleanField(verbose_name='Avisos')),
            ],
        ),
    ]
