# Generated by Django 4.2.2 on 2023-07-05 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figura',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.origen', verbose_name='Origen'),
        ),
    ]
