# Generated by Django 4.2.2 on 2023-07-05 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_figura_id_alter_figura_origen_alter_origen_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figura',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='figura',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.origen', verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='origen',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
