# Generated by Django 4.2.2 on 2023-07-06 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_alter_figura_imagen_alter_origen_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/fabricante', verbose_name='Imagen')),
            ],
        ),
        migrations.AlterField(
            model_name='figura',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.fabricante', verbose_name='Fabricante'),
        ),
    ]
